port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090

proxy-providers:
	'国内':
		type: http
		path: /国外.txt
		url: https://api.faststream.top/5bC8546b77yB5L2g6Kej5oiR5a+G5bmy5Zib77yf/download/%E5%9B%BD%E5%86%85?arget=Clash
		interval: 300
		health-check:
			enable: true
			url: http://www.gstatic.com/generate_204
			interval: 300
	'国外':
		type: http
		path: /国内.txt
		url: https://api.faststream.top/5bC8546b77yB5L2g6Kej5oiR5a+G5bmy5Zib77yf/download/%E5%9B%BD%E5%A4%96?target=Clash
		interval: 300
		health-check:
			enable: true
			url: http://www.gstatic.com/generate_204
			interval: 300

proxy-groups:
	- name: 国内代理
	  type: select
	  proxies:
	  	- 国内
	- name: 国外代理
	  type: select
	  proxies:
	  	- 国外
	- name: ADBlock
	  type: select
	  proxies:
	  	- DIRECT
		- REJECT

rule-providers:
	externalrule: AD
	type: http
	behavior: classical
	path: ./reject.txt
	url: https://github.com/Loyalsoldier/clash-rules/releases/download/202211222241/reject.txt
	interval: 300
rule:
	- RULE-SET,AD,REJECT
	- GEOIP,CN,国内
	- GEOIP,!CN,国外
	- MATCH,国外